---
- name: Import common macbook playbook
  import_playbook: macbook-common.yml

- name: Configure Work MacBook
  hosts: work
  roles: []

- name: Import post task playbook
  import_playbook: post-tasks.yml
